safe: true
lsi: false

root_url: http://kushagragour.in
title: Kushagra Gour- Creativity freak!
permalink: /blog/:year/:month/:title/
highlighter: rouge

lab_projects:
- name: "Web Maker"
  link: "web-maker/"
  desc: "Chrome extension to convert your new tab into a web playground"
- name: "superplaceholder.js"
  link: "superplaceholderjs/"
  desc: "Super charge your input placeholders"
- name: "screenlog.js"
  link: "https://github.com/chinchang/screenlog.js"
  desc: "Bring console.log on the screen"
- name: "Code-Blast Codemirror"
  link: "https://kushagragour.in/code-blast-codemirror/demo/index.html"
  desc: "Particle blasts while you type in Codemirror"
- name: "lollipop.css"
  link: "lollipop.css/"
  desc: "Android Lollipop animations in CSS"
- name: "Kalu"
  link: "kalu/"
  desc: "Calculator concept for long and inter-linked calculations"
- name: "Prototyp"
  link: "http://prototyp.in"
  desc: "App for quick and easy interaction prototyping"
- name: "konsole.table"
  link: "https://www.npmjs.com/package/konsole.table"
  desc: "console.table polyfill for Node.js"
- name: "cta.js"
  link: "ctajs/"
  desc: "A JavaScript library to animate your 'action-to-effect' paths."
- name: "Hint.css"
  link: "hint/"
  desc: "A tooltip library in CSS for your lovely websites"
- name: "piCSSel-art"
  link: "picssel-art/"
  desc: "App to draw pixel art with CSS!"
- name: "Iso-Blocks"
  link: "isoblocks/"
  desc: "Write using isometric blocks"

games:
- name: "Chal Jhoote"
  link: "chal-jhoote"
- name: "Feed the Gods"
  link: "feed-the-gods"
- name: "Save Me (LD23)"
  link: "saveme"
- name: "Beat Sight"
  link: "beat-sight"
- name: "Fun With Force"
  link: "fun-with-force"
- name: "Chef of War"
  link: "chef-of-war"
